username=input("введите имя пользователя ")
print("имя пользователя", username)
title1=input("введите заголовок заметки №1")
title2=input("введите заголовок заметки №2")
title3=input("введите заголовок заметки №3")
a = [title1, title2, title3]
print("заголовок заметки", a)
content=input("введите описание заметки ")
print("описание заметки", content)
status=input("введите статус выполнения заметки ")
print("статус заметки", status)
created_date=input("введите дату начала в формате день-месяц-год ")
print("дата создания заметки", created_date)
issue_date=input("введите дату планируемого окончания в формате день-месяц-год ")
print("дата истечения заметки", issue_date)