username=input("введите имя пользователя ")
print("имя пользователя", username)
title=input("введите заголовок заметки ")
print("заголовок заметки", title)
content=input("введите описание заметки ")
print("описание заметки", content)
status=input("введите статус выполнения заметки ")
print("статус заметки", status)
created_date=input("введите дату начала в формате день-месяц-год ")
print("дата создания заметки", created_date)
issue_date=input("введите дату планируемого окончания в формате день-месяц-год ")
print("дата истечения заметки", issue_date)